[package]
name = "gdext_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", features = ["experimental-wasm", "lazy-function-tables"] }
